### Get User Data
GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzI5NzQ3MTMsImV4cCI6MTY3MzA2MTExM30.yLEXr93n-48p1oY3qlnt3C_-5gCwtNt3LsfknWVjMrw

### Get Data Rumah Sakit
GET http://localhost/apisirs/rumahsakit/3174063
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMzLCJuYW1hIjoiUlMgS2Fua2VyIERoYXJtYWlzIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQxOTU1NDMsImV4cCI6MTY3NDE5NTYwM30.01KPNuI_o5_0rgFHqtxJR2TaO4QaFHyERBsHk7w8CB0

### Insert New User
POST http://localhost/api/users
Content-Type: application/json

{
    "nama": "dwip",
    "email": "kotakelektronik@gmail.com",
    "password": "12345",
    "rsId": "3174063"
}

### Login
POST http://localhost/apisirs/login
Content-Type: application/json

{
    "userName": "3174063",
    "password": "12345"
}

### Logut
DELETE http://localhost/apisirs/logout

### Get Token
GET http://localhost/apisirs/token

### Jenis Pelayanan RL 3.1
GET http://localhost/apisirs/jenispelayanan?rlid=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQwMzcxMDEsImV4cCI6MTY3NDAzNzE2MX0.T_4ek7zpmyzCq-CIK6sWUrqjgukVyVlhJCmFuLI20lk

### RL 3.1 READ
GET http://127.0.0.1/apisirs/rltigatitiksatu?tahun=2022
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQwMzk0NzIsImV4cCI6MTY3NDAzOTUzMn0.bBxexSzBlvKaehUsY-SRkcoyNQlUo7EWZw4BKT3zhD8

### RL 3.1 Detail READ
GET http://localhost/apisirs/rltigatitiksatudetail/76
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzM4NzkxNDYsImV4cCI6MTY3Mzg3OTIwNn0.6-JyU6zqses3YCJxTOYrnhSVjtyxiAL-eIcVJqA8EW4


### RL 3.1 CREATE
POST http://localhost/api/rltigatitiksatu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzM0MzA5MDEsImV4cCI6MTY3MzQzMDk2MX0.1bV9REaGMzogaRw53Njj3HfSH_UOUWhMBPXLfzLrwDk

{
    "tahun": 1904,
    "data": [
        {
            "jenisPelayananId": 1,
            "jumlahPasienAwalTahun": 2,
            "jumlahPasienMasuk": 3,
            "pasienKeluarHidup": 4,
            "kurangDari48Jam": 4,
            "lebihDariAtauSamaDengan48Jam":5,
            "jumlahLamaDirawat": 5,
            "jumlahPasienAkhirTahun": 6,
            "jumlahHariPerawatan": 7,
            "kelasVVIP": 8,
            "kelasVIP": 9,
            "kelas1": 10,
            "kelas2": 11,
            "kelas3": 12,
            "kelasKhusus": 13
        },
        {
            "jenisPelayananId": 2,
            "jumlahPasienAwalTahun": 3,
            "jumlahPasienMasuk": 4,
            "pasienKeluarHidup": 5,
            "kurangDari48Jam": 6,
            "lebihDariAtauSamaDengan48Jam":7,
            "jumlahLamaDirawat": 5,
            "jumlahPasienAkhirTahun": 6,
            "jumlahHariPerawatan": 7,
            "kelasVVIP": 8,
            "kelasVIP": 9,
            "kelas1": 10,
            "kelas2": 11,
            "kelas3": 12,
            "kelasKhusus": 13
        }
    ]
}

### RL 3.1 UPDATE
PATCH http://localhost/apisirs/rltigatitiksatu/76
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjYsIm5hbWEiOiJkd2lwIiwiZW1haWwiOiJrb3Rha2VsZWt0cm9uaWtAZ21haWwuY29tIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzM4NzkxNDYsImV4cCI6MTY3Mzg3OTIwNn0.6-JyU6zqses3YCJxTOYrnhSVjtyxiAL-eIcVJqA8EW4

{
    "jumlahPasienAwalTahun": 1,
    "jumlahPasienMasuk": 3,
    "pasienKeluarHidup": 4,
    "kurangDari48Jam": 4,
    "lebihDariAtauSamaDengan48Jam":5,
    "jumlahLamaDirawat": 5,
    "jumlahPasienAkhirTahun": 6,
    "jumlahHariPerawatan": 7,
    "kelasVVIP": 8,
    "kelasVIP": 9,
    "kelas1": 10,
    "kelas2": 11,
    "kelas3": 12,
    "kelasKhusus": 13
}

### RL 3.1 DELETE
DELETE http://localhost/api/rltigatitiksatu/42



###RL 3.7 CREATE
POST  http://localhost/apisirs/rltigatitiktujuh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMzLCJuYW1hIjoiUlMgS2Fua2VyIERoYXJtYWlzIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQxODg0NDIsImV4cCI6MTY3NDE4ODUwMn0.JGtwmTGKB7asawgqWP63PEk_-PViYdmtJbUrpRpwTwk

{
    "tahun": 2000,
    "data": [
        {
            "jenisKegiatanId": 2,
            "jumlah": 13
            
        },
        {
            "jenisKegiatanId": 2,
            "jumlah": 13
        }
    ]
}

### RL 3.7 READ
GET http://localhost/apisirs/rltigatitiktujuh?tahun=2000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMzLCJuYW1hIjoiUlMgS2Fua2VyIERoYXJtYWlzIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQxODg1MzIsImV4cCI6MTY3NDE4ODU5Mn0.cqf_4IWK9TLsAKD4pG0xdlrMqJoHAB9hbz0zH-W2_R4

### RL 3.7 Update
PATCH http://localhost/apisirs/rltigatitiktujuhdetail/32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDMzLCJuYW1hIjoiUlMgS2Fua2VyIERoYXJtYWlzIiwiZW1haWwiOiIzMTc0MDYzIiwicnNJZCI6IjMxNzQwNjMiLCJpYXQiOjE2NzQxODg2MTIsImV4cCI6MTY3NDE4ODY3Mn0.ktmPEvY_YDwDZrGNhf-AWW29hlPjIs5GqktWRe8geDw

{  
    "rl_tiga_titik_tujuh_id": 69,
    "user_id": 433,
    "jenis_kegiatan_id": 2,
    "jumlah": 15
}

### RL 3.7 Delete
DELETE  http://localhost/apisirs/rltigatitiktujuhdetail/54